repos:
  - repo: meta
    hooks:
    - id: identity
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.57.2
    hooks:
    - id: golangci-lint-full
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-case-conflict
      - id: detect-private-key
