server:
  port: 8080
  readTimeout: 15s
  writeTimeout: 15s
  gracefulExit: 30s
logging:
  level: -1
  encoding: console
  development: true
# Might want to cache?
metrics:
  namespace: systemd-api
  subseystem: